# Generated by Django 5.2 on 2025-05-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmTitle', models.CharField(default='', max_length=255)),
                ('cmDescription', models.TextField(blank=True)),
                ('cmStatus', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('InProgress', 'In Progress'), ('Blocked', 'BLOCKED')], default='OPEN')),
                ('cmDueDate', models.DateTimeField()),
            ],
            options={
                'ordering': ['cmTitle'],
            },
        ),
    ]
